---
vault_version: "v2025.3.1"
vault_image_digest: "sha256:a848d24db51731b8dfa77c71fcc5264e7bed13d1d0f740f49a81f8f7e083bd49"
# Cross Compile Docker Helper Scripts v1.6.1
# We use the linux/amd64 platform shell scripts since there is no difference between the different platform scripts
# https://github.com/tonistiigi/xx | https://hub.docker.com/r/tonistiigi/xx/tags
xx_image_digest: "sha256:9c207bead753dda9430bdd15425c6518fc7a03d866103c516a2c6889188f5894"
rust_version: 1.86.0 # Rust version to be used
debian_version: bookworm # Debian release name to be used
alpine_version: "3.21" # Alpine version to be used
# For which platforms/architectures will we try to build images
platforms: ["linux/amd64", "linux/arm64"]
# Determine the build images per OS/Arch
build_stage_image:
  debian:
    image: "docker.io/library/rust:{{rust_version}}-slim-{{debian_version}}"
    platform: "$BUILDPLATFORM"
  alpine:
    image: "build_${TARGETARCH}${TARGETVARIANT}"
    platform: "linux/amd64" # The Alpine build images only have linux/amd64 images
    arch_image:
      amd64: "ghcr.io/blackdex/rust-musl:x86_64-musl-stable-{{rust_version}}"
      arm64: "ghcr.io/blackdex/rust-musl:aarch64-musl-stable-{{rust_version}}"
# The final image which will be used to distribute the container images
runtime_stage_image:
  debian: "docker.io/library/debian:{{debian_version}}-slim"
  alpine: "docker.io/library/alpine:{{alpine_version}}"
